version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_gin
    environment:
      POSTGRES_USER: ginuser
      POSTGRES_PASSWORD: ginpass
      POSTGRES_DB: gindb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
